src/pages/Home/Home.jsx, src/styles/HomeStyle/HomeStyle.js
=> feat :: LearnBtn 추가

src/pages/Dictionary/Dictionary.jsx, src/pages/Dictionary/DictionaryStyle.js, src/styles/TermStyle.js
=> feat :: Dictionary 페이지 뷰 구현

src/pages/Dictionary/TermMeaning.jsx, src/styles/TermMeaningStyle.js
=> feat :: TermMeaning 페이지 UI 개선

src/pages/Profile/Profile.jsx, src/pages/Profile/ProfileStyle.js
=> feat :: Profile 페이지 UI 개선

src/pages/Home/Home.jsx, src/styles/HomeStyle/HomeStyle.js
=> feat :: Home Btn 경로 추가

src/pages/Quiz/QuizStart.jsx, src/pages/Quiz/QuizStyle.js
=> feat :: Quiz 페이지 UI 구현

src/components/Sidebar/SidebarStyle.js
=> feat :: SideBar width 수정

src/components/Sidebar/Sidebar.jsx
=> feat :: SideBar isActive 경로 추가

src/pages/Tutorial/GrapeSeedStyle.js
=> feat :: GrapeSeed margin 수정

src/components/Sidebar/SidebarStyle.js
=> feat :: SideBar 애니메이션 추가

src/components/Sidebar/SidebarStyle.js
=> feat :: SideBar 모양 수정

src/Hooks/Login/useLogin.js, src/Hooks/Signup/useSignup.js, src/components/Term/Term.jsx, src/pages/Signup/Signup.jsx, src/styles/TermStyle.js
=> feat :: useSignup 수정

src/Hooks/Signup/useSignup.js, src/pages/Login/Login.jsx, src/pages/Signup/Signup.jsx, src/pages/Signup/SignupStyle.js
=> feat :: Signup 성공 로직 추가

src/Hooks/Login/useLogin.js, src/pages/Login/Login.jsx
=> feat :: Login 로직 수정

src/Hooks/Login/useLogin.js, src/components/Term/Term.jsx, src/pages/Dictionary/Dictionary.jsx, src/pages/Dictionary/DictionaryStyle.js, src/pages/Signup/Signup.jsx, src/styles/TermStyle.js
Reverts teamMinari/NewMinariWeb#20
=> Revert "Dictionary"

src/pages/Profile/ProfileStyle.js
=> feat :: Profile ui 수정

src/pages/Dictionary/DictionaryMain.jsx, src/pages/Dictionary/DictionaryMainStyle.js
=> fix :: Dictionary ui 수정

src/components/Header/Header.jsx, src/pages/Profile/Profile.jsx, src/pages/Profile/ProfileStyle.js
=> feat :: Token 프로필 변경 구현

package.json, postcss.config.js, src/components/Header/Header.jsx, src/components/Header/HeaderStyle.js, src/index.css, src/pages/Profile/ModalStyle.css, src/pages/Profile/Profile.jsx, src/pages/Profile/ProfileStyle.js, tailwind.config.js
=> feat :: Profile 프로필 변경

src/pages/Tutorial/Tutoirial.jsx, src/pages/Tutorial/TutoirialStyle.js
=> feat :: Grapes 받기
